services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MAILERSEND_API_KEY_SCHNELLSITE=${MAILERSEND_API_KEY_SCHNELLSITE}
      - MAILERSEND_API_KEY_EGOSTITELJ=${MAILERSEND_API_KEY_EGOSTITELJ}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3 